language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - echo "Running tests with pytest"
  - pytest
  - echo "Dummy API Token for testing: 1234567890abcdef1234567890abcdef"

