language: node_js
node_js:
  - "18.19.0"

os: linux
dist: focal

env:
  global:
    - PLAN_ID=999999  # invalid plan_id

install: skip

script:
  - echo "Running tests..."
  - echo "Using PLAN_ID=$PLAN_ID"

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - npm install -g npm@9

deploy:
  provider: npm
  email: "${NPMJS_EMAIL}"
  api_key: "${NPMJS_API_KEY}"
  skip_cleanup: true
  on:
    tags: true
