language: node_js
node_js:
  - "18.19.0"

os: linux
dist: focal

install: skip  # No installation step if not required

script:
  - echo "Running tests..."

before_deploy:
  # Downgrade npm to version 9 before deploying
  - npm install -g npm@9

deploy:
  provider: npm
  email: "${NPMJS_EMAIL}"
  api_key: "${NPMJS_API_KEY}"
  skip_cleanup: true
  on:
    tags: true
