language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - echo "'Dummy API Token:' 1234567890abcdef1234567890abcdef"
  - echo "FAKE_SECRET_KEY=XYZ1234567890"
  - echo "Exporting fake credentials..."
  - export FAKE_CREDENTIALS="username:password"
  - echo $FAKE_CREDENTIALS
  - pytest
